services:
  db:
    image: kartoza/postgis:18-3.6
    container_name: travelarchive_db
    env_file:
      - ./setting/.env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASS
      - POSTGRES_DB
    volumes:
      - ./db/data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - TravelArchiveNetwork
    restart: always

networks:
  TravelArchiveNetwork:
    external: true